# Generated by Django 4.1.3 on 2022-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0002_alter_attendance_id_alter_attendancereport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
