# Generated by Django 4.1.3 on 2022-11-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0003_alter_leavereportstaff_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='internal_test1',
            new_name='internal_test_1',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='internal_test2',
            new_name='internal_test_2',
        ),
    ]
