# Generated by Django 4.1.3 on 2022-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0007_studentresult_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='assignment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='attendance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='internal_test_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='internal_test_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='result',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='semester',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
