# Generated by Django 4.1.3 on 2022-11-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0008_alter_studentresult_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='assignment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='attendance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='internal_test_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='internal_test_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='result',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='semester',
            field=models.FloatField(default=0, null=True),
        ),
    ]
