# Generated by Django 4.1.3 on 2022-11-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0012_customuser_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='DOB',
            new_name='date_of_birth',
        ),
    ]
