# Generated by Django 4.1.3 on 2022-11-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0013_rename_dob_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('room_pwd', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('session_years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College_App.session')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College_App.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College_App.subject')),
            ],
        ),
    ]
