# Generated by Django 4.1.3 on 2022-11-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_App', '0014_onlineclassroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineClassRoom',
        ),
    ]
